# Generated by Django 3.1.7 on 2021-03-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('data_noticia', models.DateField()),
                ('fonte', models.CharField(max_length=50)),
                ('conteudo', models.TextField()),
                ('url', models.URLField()),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
    ]
