# Generated by Django 4.0.3 on 2022-04-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['data_noticia']},
        ),
    ]
